baseURL = "https://scintillating.us"
languageCode = "en-us"
title = "Scintillating"

theme = "meghna"

[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"

    # footer
    [params.footer]
        copyright = "Scintillating"
        copyrightURL = "https://scintillating.us"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"